
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.BackingStoreException;
import javax.swing.JTextField;
import java.util.prefs.Preferences;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class gpaCalculator extends javax.swing.JFrame {
    Preferences pref = Preferences.userNodeForPackage(Settings.class);

    private double classGPA;
    private double class1GPA;
    private double class2GPA;
    private double class3GPA;
    private double class4GPA;
    private double class5GPA;
    
    private double classQP;
    private double class1QP;
    private double class2QP;
    private double class3QP;
    private double class4QP;
    private double class5QP;
    private double totQP;
    
    private double classCredit;
    private double class1Credit;
    private double class2Credit;
    private double class3Credit;
    private double class4Credit;
    private double class5Credit;
    
    private double cumGPA;
    private double totCredit;
    private double sumCredit;
    private double currentSemGPA;

   
    public gpaCalculator() {
        
        initComponents();
        initialize();
        startUp(); 
    }
    
    private double gradeConverter(String grade)
    {
        if (grade.equalsIgnoreCase("a+"))
        {
            return 4.0;
        }
        if (grade.equalsIgnoreCase("a"))
        {
            return 4.0;
        }
        if (grade.equalsIgnoreCase("a-"))
        {
            return 3.7;
        }
        if (grade.equalsIgnoreCase("b+"))
        {
            return 3.3;
        }
        if (grade.equalsIgnoreCase("b"))
        {
            return 3.0;
        }
        if (grade.equalsIgnoreCase("b-"))
        {
            return 2.7;
        }
        else 
        {
            return 0;
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Class1 = new javax.swing.JLabel();
        Class2 = new javax.swing.JLabel();
        Class3 = new javax.swing.JLabel();
        Class = new javax.swing.JLabel();
        Class4 = new javax.swing.JLabel();
        Class5 = new javax.swing.JLabel();
        Spinner = new javax.swing.JComboBox<>();
        Spinner1 = new javax.swing.JComboBox<>();
        Spinner2 = new javax.swing.JComboBox<>();
        Spinner3 = new javax.swing.JComboBox<>();
        Spinner4 = new javax.swing.JComboBox<>();
        Spinner5 = new javax.swing.JComboBox<>();
        done = new javax.swing.JButton();
        semGPA = new javax.swing.JTextField();
        settings = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        semGPA1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Class1.setText("Class 2");

        Class2.setText("Class 3");

        Class3.setText("Class 4");

        Class.setText("Class 1");

        Class4.setText("Class 5");

        Class5.setText("Class 6");

        Spinner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "L" }));
        Spinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpinnerActionPerformed(evt);
            }
        });

        Spinner1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "L" }));
        Spinner1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Spinner1ActionPerformed(evt);
            }
        });

        Spinner2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "L" }));
        Spinner2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Spinner2ActionPerformed(evt);
            }
        });

        Spinner3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "L" }));
        Spinner3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Spinner3ActionPerformed(evt);
            }
        });

        Spinner4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "L" }));
        Spinner4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Spinner4ActionPerformed(evt);
            }
        });

        Spinner5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "L" }));
        Spinner5.setToolTipText("");
        Spinner5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Spinner5ActionPerformed(evt);
            }
        });

        done.setBackground(new java.awt.Color(0, 0, 255));
        done.setText("Done");
        done.setToolTipText("");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        semGPA.setEditable(false);
        semGPA.setHorizontalAlignment(JTextField.CENTER);
        semGPA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        semGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semGPAActionPerformed(evt);
            }
        });

        settings.setBackground(new java.awt.Color(0, 255, 0));
        settings.setText("Settings");
        settings.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        settings.setInheritsPopupMenu(true);
        settings.setName(""); // NOI18N
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("GPA Calculator 2.0");

        jLabel1.setText("Semester GPA:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Cumulative GPA:");

        semGPA1.setEditable(false);
        semGPA1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        semGPA1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        semGPA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semGPA1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(9, 72, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(semGPA)
                            .addComponent(done, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(semGPA1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Class, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Class2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Class3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Class4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Class1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE))
                            .addComponent(Class5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Spinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Spinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Spinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Class, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Class1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Class2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Class3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Class4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Class5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semGPA1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void semGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semGPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semGPAActionPerformed

    private void SpinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpinnerActionPerformed
        classGPA = gradeConverter(Spinner.getSelectedItem().toString());
        pref.putInt("classGrade", Spinner.getSelectedIndex());
    }//GEN-LAST:event_SpinnerActionPerformed

    private void Spinner1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Spinner1ActionPerformed
       class1GPA = gradeConverter(Spinner1.getSelectedItem().toString());
       pref.putInt("class1Grade", Spinner1.getSelectedIndex());
    }//GEN-LAST:event_Spinner1ActionPerformed

    private void Spinner2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Spinner2ActionPerformed
        class2GPA = gradeConverter(Spinner2.getSelectedItem().toString());
        pref.putInt("class2Grade", Spinner2.getSelectedIndex());
    }//GEN-LAST:event_Spinner2ActionPerformed

    private void Spinner3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Spinner3ActionPerformed
       class3GPA = gradeConverter(Spinner3.getSelectedItem().toString());
       pref.putInt("class3Grade", Spinner3.getSelectedIndex());
    }//GEN-LAST:event_Spinner3ActionPerformed

    private void Spinner4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Spinner4ActionPerformed
      class4GPA = gradeConverter(Spinner4.getSelectedItem().toString());
      pref.putInt("class4Grade", Spinner4.getSelectedIndex());
    }//GEN-LAST:event_Spinner4ActionPerformed

    private void Spinner5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Spinner5ActionPerformed
      class5GPA = gradeConverter(Spinner5.getSelectedItem().toString());
      pref.putInt("class5Grade", Spinner5.getSelectedIndex());
    }//GEN-LAST:event_Spinner5ActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
     semesterGPA();
     cumulativeGPA();
     
    }//GEN-LAST:event_doneActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
    new Settings().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_settingsActionPerformed

    private void semGPA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semGPA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semGPA1ActionPerformed

 private void initialize(){
     String className = pref.get("Class", "");
     String class1Name = pref.get("Class1", "");
     String class2Name = pref.get("Class2", "");
     String class3Name = pref.get("Class3", "");
     String class4Name = pref.get("Class4", "");
     String class5Name = pref.get("Class5", "");
     
     if (!className.equalsIgnoreCase("Enter Class") || !className.equalsIgnoreCase("")){
         Class.setText(className);
     }
     if (!class1Name.equalsIgnoreCase("Enter Class") || !class1Name.equalsIgnoreCase("")){
         Class1.setText(class1Name);
     }
     if (!class2Name.equalsIgnoreCase("Enter Class") || !class2Name.equalsIgnoreCase("")){
         Class2.setText(class2Name);
     }
     if (!class3Name.equalsIgnoreCase("Enter Class") || !class3Name.equalsIgnoreCase("")){
         Class3.setText(class3Name);
     }
     if (!class4Name.equalsIgnoreCase("Enter Class") || !class4Name.equalsIgnoreCase("")){
         Class4.setText(class4Name);
     }
      if (!class5Name.equalsIgnoreCase("Enter Class") || !class5Name.equalsIgnoreCase("")){
         Class5.setText(class5Name);
     }
      
      if (className.equalsIgnoreCase("Enter Class") || className.equalsIgnoreCase("")){
         Class.setText(" ");
         Spinner.setVisible(false);
     }
     if (class1Name.equalsIgnoreCase("Enter Class") || class1Name.equalsIgnoreCase("")){
         Class1.setText(" ");
         Spinner1.setVisible(false);
     }
     if (class2Name.equalsIgnoreCase("Enter Class") || class2Name.equalsIgnoreCase("")){
         Class2.setText(" ");
         Spinner2.setVisible(false);
     }
     if (class3Name.equalsIgnoreCase("Enter Class") || class3Name.equalsIgnoreCase("")){
         Class3.setText(" ");
         Spinner3.setVisible(false);
     }
     if (class4Name.equalsIgnoreCase("Enter Class") || class4Name.equalsIgnoreCase("")){
         Class4.setText(" ");
         Spinner4.setVisible(false);
     }
      if (class5Name.equalsIgnoreCase("Enter Class") || class5Name.equalsIgnoreCase("")){
         Class5.setText(" ");
         Spinner5.setVisible(false);
     }
     
      classCredit = Double.parseDouble(pref.get("Credit", "0"));
      class1Credit = Double.parseDouble(pref.get("Credit1", "0"));
      class2Credit = Double.parseDouble(pref.get("Credit2", "0"));
      class3Credit = Double.parseDouble(pref.get("Credit3", "0"));
      class4Credit = Double.parseDouble(pref.get("Credit4", "0"));
      class5Credit = Double.parseDouble(pref.get("Credit5", "0"));
        
      if (pref.get("cumGPA", "0") == ""){
          cumGPA = 0;
         
      }
      if (pref.get("totCredit", "0") == ""){
           totCredit = 0;
      } else{
      System.out.println(pref.get("cumGPA", "0"));
      System.out.println(pref.get("totCredit", "0"));
      //cumGPA = Double.parseDouble(pref.get("cumGPA", "0"));
      //totCredit = Double.parseDouble(pref.get("totCredit", "0"));
      }
      
      semGPA.setText(pref.get("semGPA", ""));
      semGPA1.setText(pref.get("newCumGPA", ""));
      
      Spinner.setSelectedIndex(pref.getInt("classGrade", 0));
      Spinner1.setSelectedIndex(pref.getInt("class1Grade", 0));
      Spinner2.setSelectedIndex(pref.getInt("class2Grade", 0));
      Spinner3.setSelectedIndex(pref.getInt("class3Grade", 0));
      Spinner4.setSelectedIndex(pref.getInt("class4Grade", 0));
      Spinner5.setSelectedIndex(pref.getInt("class5Grade", 0));

      
 }
 private void semesterGPA(){
     classQP = classGPA * classCredit;
     class1QP = class1GPA * class1Credit;
     class2QP = class2GPA * class2Credit;
     class3QP = class3GPA * class3Credit;
     class4QP = class4GPA * class4Credit;
     class5QP = class5GPA * class5Credit;
     
     sumCredit = classCredit + class1Credit + class2Credit + class3Credit + class4Credit + class5Credit;
     totQP = classQP + class1QP + class2QP + class3QP + class4QP + class5QP;
     
     currentSemGPA = totQP / sumCredit;
     String test = String.valueOf(currentSemGPA);
     
     if (test.length() > 4)
      {
          test = test.substring(0,5);
      }
     if (test.length() == 4)
      {
          test = test.substring(0,4) + "00000";
          test = test.substring(0,5);
      }
      if (test.length() == 3)
      {
          test = test.substring(0,3) + "00000";
          test = test.substring(0,5);
      }
      if (test.length() == 2) 
      {
         test = test.substring(0,2) + "000000";
         test = test.substring(0,5); 
      }
      else
      {
          test = test;
      }
      semGPA.setHorizontalAlignment(JTextField.CENTER);
      semGPA.setText(test); 
      
      
     pref.put("semGPA", test);
     
     

     
     
    
 }
 private void cumulativeGPA(){
     double newCumGPA = ((cumGPA*totCredit)+(currentSemGPA*sumCredit))/(totCredit+sumCredit);
     String test1 = String.valueOf(newCumGPA);
     
     if (test1.length() > 4)
      {
          test1 = test1.substring(0,5);
      }
     if (test1.length() == 4)
      {
          test1 = test1.substring(0,4) + "00000";
          test1 = test1.substring(0,5);
      }
      if (test1.length() == 3)
      {
          test1 = test1.substring(0,3) + "00000";
          test1 = test1.substring(0,5);
      }
      if (test1.length() == 2) 
      {
         test1 = test1.substring(0,2) + "000000";
         test1 = test1.substring(0,5); 
      }
      else
      {
          test1 = test1;
      }
      semGPA1.setHorizontalAlignment(JTextField.CENTER);
      semGPA1.setText(test1); 
      
      
     pref.put("newCumGPA", test1);
 }
 private void startUp(){
     if (pref.getInt("66",0) == 0){
    JOptionPane.showMessageDialog(this,
    "Welcome to the GPA Calculator 2.0. Enter Settings to Input Your Classes!");
    pref.putInt("66", 1);
     }
      Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
          
 }
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(() -> {
            new gpaCalculator().setVisible(true);
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Class;
    private javax.swing.JLabel Class1;
    private javax.swing.JLabel Class2;
    private javax.swing.JLabel Class3;
    private javax.swing.JLabel Class4;
    private javax.swing.JLabel Class5;
    private javax.swing.JComboBox<String> Spinner;
    private javax.swing.JComboBox<String> Spinner1;
    private javax.swing.JComboBox<String> Spinner2;
    private javax.swing.JComboBox<String> Spinner3;
    private javax.swing.JComboBox<String> Spinner4;
    private javax.swing.JComboBox<String> Spinner5;
    private javax.swing.JLabel Title;
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField semGPA;
    private javax.swing.JTextField semGPA1;
    private javax.swing.JButton settings;
    // End of variables declaration//GEN-END:variables
}
